### ISSUE TITLE
expunge TStime(), timesynch.c et al.

### ISSUE THREAD

**Issue by kaniini** [rabbitircd/rabbitircd#11]
TStime() is bad, should be removed.

Instead encourage users to use chrony or some other ntpd.  In 2013, there's no reason to need to override the system clock.

**Comment by falconkirtaran** [comment]
Todo: remove TSoffset and TStime()

**Comment by kaniini** [comment]
We should keep TSTime() itself, because time(NULL) will cause thousands of syscalls per second.  Instead, cache the timestamp when eventloop sleep concludes.

**Comment by falconkirtaran** [comment]
Ok, this works too.  I didn't think the overhead was really so great that it was necessary to cache the result of time(NULL), but it can't hurt either.

**Comment by kaniini** [comment]
It can be pretty bad.  We're talking a difference of 10-20% CPU use under moderate load.
