### ISSUE TITLE
random.c read() return value ignored

### ISSUE THREAD

**Issue by falconkirtaran** [rabbitircd/rabbitircd#15]
random.c: In function 'init_random':
random.c:184:7: warning: ignoring return value of 'read', declared with attribute warn_unused_result [-Wunused-result]
   read(fd, &rdat.rnd, sizeof(rdat.rnd));
       ^

**Comment by kaniini** [comment]
Since we depend on OpenSSL as a hard dependency, why don't we just replace this stuff to calls to OpenSSL RAND?

**Comment by falconkirtaran** [comment]
Yes.  This should be closed when random.c is replaced with that.  We could also use normal rand() with impunity when we don't care whether what comes out is cryptographically random.
