### ISSUE TITLE
Remove tunefile support

### ISSUE THREAD

**Issue by falconkirtaran** [rabbitircd/rabbitircd#28]
The tunefile contains nothing but the timestamp delta (computed anew on link anyway) and the max user count, and the first element has been removed with TSoffset in #11.  Therefore, the format is broken.  This feature is not worth saving.

**Comment by kaniini** [comment]
why not just remove support for tunefile.  if all it contains is the local user count max, do we really need it?

**Comment by falconkirtaran** [comment]
Indeed, we really don't.
