### ISSUE TITLE
Several makefile and config issues

### ISSUE THREAD

**Issue by falconkirtaran** [rabbitircd/rabbitircd#29]
- The format of modules.conf is wrong
- The makefile install job refers to nonexistent files
- There are syntax errors in the example config

**Comment by kaniini** [comment]
modules.conf is correct, as it is supposed to bolt .so onto the end.  maybe look at strace log if you are having a problem...

**Comment by falconkirtaran** [comment]
The sample config files are working now as long as there is a symlink to modules/ in the working directory.
