### ISSUE TITLE
Secure channel oddness

### ISSUE THREAD

**Issue by HelixSpiral** [rabbitircd/rabbitircd#38]
Currently there are 2 channel modes for SSL channels, +Z and +z, +Z being used if not all of the users in the channel are actually on an ssl-connection and +z being used if they are.

This, to me, sounds like a rather weird setup and I would rather see +Z removed entirely and this reverted to the original usage of just +z for completely ssl channels.

**Comment by kaniini** [comment]
Well... there is a problem with this.

If we do this, then we lose link compatibility with Unreal 3.2.

@falconkirtaran is unreal 3.2 link compatibility important to us, in your opinion?

**Comment by falconkirtaran** [comment]
Link compatibility with 3.2 should be viewed as an upgrade feature only.  However, upgrades would be rather painful without 3.2 link compatibility for at least one version.

That said, this is not a correct assessment of chmodes +zZ.  +z is an oper-settable mode which requires that only SSL users can join.  +Z is a server-only mode which indicates that all the users on the channel actually are using SSL, if +z is set, which is important to know: imagine you set +z while a cleartext user was in the channel already, or someone not using SSL got SAJOINed to the channel.

If +Z is set on a channel while either the channel is -z or there is a non-SSL user in the channel, that is a bug that we need to fix and I'd appreciate repro for it.

**Comment by HelixSpiral** [comment]
"+Z is a server-only mode which indicates that all the users on the channel actually are using SSL"
This is not true. +Z is only used when the channel has non-SSL users.

When setting +z if there is a non-SSL user in the channel it should either return an error or kick all non-SSL users.

If a user is sajoin'd in they should be immediately kicked or the +z removed.

IMO maintaining backwards compatibility with the ircd this was forked from will hurt in the long run. It will only help users migrate in the near future. After 2-3 or more versions have passed the ability to maintain backwards compatibility will be gone and you'll have wasted time keeping the link workable when you could have been developing other things.

**Comment by falconkirtaran** [comment]
That is not how it is documented in the version of unreal we forked from.

It's advantageous to maintain link compatibility for exactly one version, and deprecate (only) anything that is removed which would impact compatibility.  This is so that a network of several servers could upgrade one at a time without disrupting the whole network for any longer than it takes to upgrade the hub.
