### ISSUE TITLE
#define DEBUGMODE //... this doesn't work - GCC crashes with "no member named (next|prev)" on s_misc.c

### ISSUE THREAD

**Issue by janicez** [rabbitircd/rabbitircd#47]
Title says it all.

**Comment by kaniini** [comment]
Have you considered going away?

**Comment by patosar** [comment]
@kaniini wtf is wrong with you nenolod?

**Comment by falconkirtaran** [comment]
They have a private dispute.

This software isn't really ready to use yet - expect all kinds of crashes, let alone compile failures.  However, I might get time to fix some of this stuff.
